spring.application.name=springboot-jpa
spring.datasource.url=jdbc:mysql://localhost:3306/db_springboot
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=create -> Usar solo la primera vez que se ejecuta el programa
# para generar las columnas vacias, si no se quita luego esta linea, los datos de volveran a resetear.

# este es otro modo de que no se borre los datos, cambiar CREATE POR UPDATE
spring.jpa.hibernate.ddl-auto=update 
